### ISSUE TITLE
Needs Work !

### ISSUE THREAD

**Issue by thecodechef** [nsandman09/nml#1]
Well I like your idea but your `parser.py` has some things it shouldn't and my main problem is that your readme doesn't match your iinstructions but here are a few suggestions to help
## Block Tags

```
   $head

   %
```

turns into 

```
   <head>

   </head>
```
## Inline Tags

```
@link (rel: stylesheet href: css/main.js)
```

turns into

```
<link rel="stylesheet" href="css/main.css" />
```

Oh and your parser doesn't do anything with the ampersand like your readme says it does 

well here is a fix for that 
## Logic Tags

```
&for item in items
  &if item.name
    $h2(id: item.id) item.name%
  &else
    $h2(id: empty_tag)'Sorry No Name Here'%
  &endif
&endfor
```

here is a good example
https://github.com/thecodechef/photo_library/blob/master/Screenshot.png

**Comment by nsandman** [comment]
@thecodechef: Thanks for the feedback!
I'm sorry that the parser doesn't currently match the README (I've been working on it on my local copy, and my changes just arent't quite there.) In that copy, I'm using ampersands for a macro syntax (and they used to be used for attributes, which is probably what's in the README). As such, there is a new "preprocess" function which not only deals with macros, but converts NML-specific tags such as `@css ...` to `@link (rel: stylesheet, type: text/css, ...)`, so the parser won't have to make any exceptions (which is always good). The main difference between how the two work is that the preprocessor parses line by line, allowing it to see ahead and make sure it made no erroneous substitutions.

Another option would be to use `@css` and `@js` to convert to inline tags (meaning it would effectively paste in the contents in from the URL given, allowing it to check for several paths). This would be, as I see it, an unobtrusive way of doing what you suggested with your extension correcting.

I also do like your logic tags idea, so thanks for suggesting that! I'll implement it once macros work to my satisfaction.

Also, what you described _is_ how block tags work. If that wasn't explained properly, I'll update the README when I get the chance. Sorry, and thanks for bringing that to my attention.

I'd like to say thanks one more time. Your feedback has been noted and I'm really glad you've taken the time to look at my project.

**Comment by nsandman** [comment]
Also, what you've described has been the syntax for inline tags since I rewrote the parser. The only difference is that attributes are separated by a comma.

**Comment by thecodechef** [comment]
the problem though is that the  inline tags don't give you an actual inline tag it gives you a block tag and putting the ending tag inside of the body ending tag

**Comment by thecodechef** [comment]
the only one that it works for is the title tag instead giving you `/>` it gives you `</linkbody>` or something to that effect

oh one more thing  to point out  what @FichteFoll was talking about just take the tmLanguage file and put it into the github repo get rid of the bitbucket and it should be all good from there after you do your next release

**Comment by thecodechef** [comment]
never mind  i just tried the inline tags on style,h1-h6 & more so it does work for more than the title tag my bad

**Comment by nsandman** [comment]
@thecodechef  Alright, thanks! I'll do that when I get a chance.

**Comment by nsandman** [comment]
Implemented logic tags, so I'm closing this now.
